apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 4  # Create 4 replicas
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: my-docker-image:latest  # Replace with your Docker image name
        ports:
        - containerPort: 80  # Replace with the port your container is listening on
